# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FDwaDnae-CpngIrvK_eWSltc8U45YWK
"""

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('cars.jpeg')

if image is None:
    print("Error: Could not load image 'cars.jpeg'. Make sure the file exists in the current directory.")
else:
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    cv2_imshow(image)
    cv2_imshow(gray_image)
    cv2.imwrite('photo_gray.jpg', gray_image)
    print("Grayscale image saved as 'photo_gray.jpg'.")

    cv2.waitKey(0)
    cv2.destroyAllWindows()